iine/iiname

- .travis.yml
travis and heroku integration.
> Add heroku setttings to .travis.yml

- app/assets/javascripts/application.js
> Remove turbolinks

- .travis.yml
Add slack integration
slackとtravis-ciの連携設定を行ないます。
> Add slack integration

- test/controllers/suggestions_controller_test.rb
- test/fixtures/suggestions.yml
https://trello.com/c/VGXVBZBZ/36--
こちらのtrelloのカードの対応です。
簡単なテストの実装をしてみました。
controllerの実装自体がまだ単純過ぎるのであまり具体的なテストにはなってませんが、こちらを参考にしてみてください。
@kinchan33 さんや @harakoji さんは単体テストなどのイメージは掴めるかと思いますが、 @atakei さんや @KenyaOkada さんは意味がよくわからないかもしれません。
基本的には、テスト対象のクラス・メソッドにて「こうなるべき」という動きをテストで確認するためのものです。
https://github.com/iine/iiname/pull/10/files#diff-1d61357f88cd3333a5a485fa2b27d399R14
例えば、これなどは、`index` メソッド内では、Suggestionクラスの全てのデータが取得されてcontrollerのメンバ変数 `suggestions` に格納されるはずなので、それを確認しています。
https://github.com/iine/iiname/pull/10/files#diff-1d61357f88cd3333a5a485fa2b27d399R26
これなどは、Suggestionクラスの全件の中の任意の1件(ランダム)がcontrollerのメンバ変数 `suggestion` に格納されるはずなので、Suggestion全件の中にこれがあることを確認しています。
> Implement some test of suggestion conrtoller

- README.md
> Modify README.md add link

- app/assets/javascripts/misc/utils.js
- app/assets/stylesheets/main.css.scss
- app/views/layouts/application.html.erb
- public/partials/main.html
feature toggleの簡易的な実装です。
htmlのclassに `feature-toggle` を指定すれば、本番環境のみその要素が非表示になります。
本番環境でも、jsなどのコンソールで `ftoggle()` を実行すれば表示は可能です。
> Add feature toggle

- app/views/layouts/application.html.erb
提案されたチーム名のリストの並び順を新しいものが上になるように修正しました。
> Fixed suggested keyword ordering.

- app/assets/javascripts/index_controller.js
- app/assets/javascripts/main_controller.js
- app/assets/javascripts/names_controller.js
- app/controllers/names_controller.rb
- config/routes.rb
- public/partials/names.html
- test/controllers/names_controller_test.rb
> 名前入力の第一弾実装

- app/assets/javascripts/interests_controller.js
- app/assets/stylesheets/main.css.scss
- app/controllers/suggestions_controller.rb
- public/partials/interests.html
画像を選択する機能にAngularJSを使った修正を加える予定です。
> Use of AngularJS (interest_image)

- app/views/layouts/application.html.erb
- app/views/prefectures/index.html.erb
- app/views/suggestions/index.html.erb
MainController部分をyeild内に入れてレイアウトを修正しました。
> Change MainController into yeild

- .pryrc
- Gemfile
- Gemfile.lock
- app/controllers/suggestions_controller.rb
- config/application.rb
- lib/iiname/engine.rb
- test/controllers/suggestions_controller_test.rb
- test/lib/iiname/engine_test.rb
- test/support/google-search-helper.rb
- test/test_helper.rb
とりあえず、WEB検索で作ってみました。
他にも本とかBlogとか検索できますが、どれが面白いかは色々今後試してみるとして、取り敢えずのバージョンとしてはこれで良いかな、と。
> いいネームエンジンのベース作り

- Gemfile
- Gemfile.lock
- app/controllers/names_controller.rb
- test/controllers/names_controller_test.rb
テストコードを修正したのと、Travisのトークンを設定しました。
どうでしょう？
> web apiでの検索

- app/controllers/suggestions_controller.rb
とりあえず、ランダムの際の検索結果をスペースでぶった切って最初のものをキーワードとするようにしてみた。
> Change keyword extracting method

- app/assets/javascripts/index_controller.js
- app/assets/javascripts/names_controller.js
取り敢えず、ランダム部分と名前の部分に二重サブミット防止を入れました。
> Add preventing double submit

- app/assets/javascripts/index_controller.js
- app/assets/javascripts/main_controller.js
- app/assets/javascripts/routes.js
- public/partials/main.html
https://trello.com/c/I8Gb0hdY/96-10
こちらの対応。
10秒ほどで切り替わる。
サーバが遅い時のために一度実行中で再度intervalが走る際にロックをチェックするようにしてある。
angularのroutingの記述もついでに修正。
> 自動suggestion

- app/controllers/suggestions_controller.rb
ランダムで表示するところの区切り文字をスペースの他にいくつか追加しました。
レビューお願いします。
> modify regex of delimiter.

- app/assets/stylesheets/main.css.scss
- config/routes.rb
> Feature/new layout, Modify footer.

- app/controllers/suggestions_controller.rb
@harakoji 
>  、。：？！"この辺をデリミタに追加してもいいかもですね。
対応してみました。いかがでしょう？間に合うかな？
> add more delimiters.

- app/assets/javascripts/interests_controller.js
- app/assets/stylesheets/main.css.scss
- app/controllers/images_controller.rb
- app/controllers/suggestions_controller.rb
- app/models/image.rb
- app/views/images/index.json.jbuilder
- app/views/suggestions/index.html.erb
- config/routes.rb
- db/migrate/20151017051320_create_images.rb
- db/schema.rb
- db/seeds.rb
- public/partials/interests.html
- test/controllers/images_controller_test.rb
- test/fixtures/images.yml
- test/models/image_test.rb
> Image table の作成

- app/controllers/suggestions_controller.rb
エンジン点火しました。如何でしょう:exclamation:
> Ignite engine.

- README.md
> Modify readme, change URL

- app/assets/javascripts/main_controller.js
> Fix empty suggestion

- app/views/suggestions/index.html.erb
> Remove feature toggle

- app/assets/stylesheets/main.css.scss
> 画像のスタイルを僅かに変更

- app/views/statuses/result.erb
social button を tweet button だけにして、きちんと結果を tweet できるようにする！
> 動くtweetボタンをつける

- app/controllers/suggestions_controller.rb
- test/controllers/suggestions_controller_test.rb
https://trello.com/c/a9fguA9p/120--
こちらのトレロの対応です。
`places[]` パラメータで建物名を受け取ります。
> Add place suggestion at suggestion controller

- app/assets/javascripts/interests_controller.js
- app/assets/javascripts/main_controller.js
- app/assets/javascripts/names_controller.js
- app/assets/javascripts/place_controller.js
直近の質問の回答だけを使ってエンジンに投げるように修正。
https://trello.com/c/coKAHUQF/128--
> Use last answer when to suggest keyword

- app/assets/javascripts/place_controller.js
以前の検索条件での結果が残ってしまっていたバグのfixです。
vm.placeに追加され続けてしまっていたので、検索タイミングで初期化するようにしました。
> Fixed persisting on LocalStorage

- public/partials/interests.html
- public/partials/place.html
> Switch the question.

- app/assets/javascripts/place_controller.js
https://trello.com/c/ZPF1OQTp/142-ui
- reduce markers.
- marker draggable.
- map double clickable.
マーカーを中心点だけに。
マーカーをドラッガブルに(同時に再検索)。
mapをダブルクリックで中心点移動(同時に再検索)。
> Change markers and map.

- app/views/layouts/application.html.erb
> Modify the file

- app/assets/javascripts/main_controller.js
- app/assets/javascripts/names_controller.js
> Fixed auto suggestion for names controller

- app/assets/stylesheets/main.css.scss
- app/views/layouts/application.html.erb
クリックすると、ページの上部に移動できるボタンを設置しました。
> ページの上部に移動するボタンの設置

- app/views/layouts/application.html.erb
Google Analyticsを使用するためのtrackingコードを追加しました。
> Add Google analytics, add tracking code

- app/assets/javascripts/interests_controller.js
- app/assets/javascripts/main_controller.js
- app/assets/javascripts/names_controller.js
- app/assets/javascripts/place_controller.js
- app/assets/stylesheets/main.css.scss
- app/views/suggestions/index.html.erb
- public/partials/interests.html
- public/partials/names.html
- public/partials/place.html
https://trello.com/c/o1PDeDOT/152--
こちらの対応。
付箋に元となる解答をキーワード、もしくは緯度経度の座標、画像で表現。
> 付箋に元となる解答情報を載せる

- License.txt
> Add the license file
